### ISSUE TITLE
No sentences_translation.json

### ISSUE THREAD

**Issue by finnwit** [3b1b/captions#160]
No file in 3b1b/captions/tree/main/2019/bayes-theorem-quick/german

**Comment by Dat-Pudding** [comment]
Same goes for pretty much the entire `./2015/` directory no matter the language.

Only `./2015/music-and-measure-theory/` got a `sentences_translation.json`

**Comment by 3b1b** [comment]
Originally I did not create sentence translation files for videos that had community contributions in the past, from the good old days when YouTube let the community submit subtitles.

I've done a first pass at pulling in the information from those community subtitles to the translation files, though it's difficult to align exactly because the timings are not perfect. Fairly soon, we'll have a beta version of an editing interface, which hopefully presents these in a somewhat reasonable manner.
