### ISSUE TITLE
Suggestion: using toml format instead of json

### ISSUE THREAD

**Issue by tintin10q** [3b1b/captions#42]
In your community post on youtube you say that it is a bit absurd to ask people to write json files. I think this is true. Non technical people can have diffulties with json files. 

I suggest that you use [toml](https://toml.io/en/). It tries to do the same as json but it is much much more human friendly.

It is also python compatible without 3rd party dependencies, so python has a toml parser in the standart library (since 3.11).

Many things already use toml like rust cargo and python poetry. 

Check it out. Its really cool.

**Comment by 3b1b** [comment]
Good to know, thanks for the suggestion. The main thing I'm contemplating right now is whether it's worth having a separate mode of doing edits entirely, with a simple web app that presents a reviewer with the English and the translation, which they can edit, and would then record a reviewer name on each piece they review.

If I stick with something purely on Github, though, toml may indeed be a better option.

**Comment by styrix560** [comment]
I personally think the web app would be the preferable option, simply because I feel like the complexity of the process of adding a suggestion on github would drive too many people away.

I did a simple contribution to test how this would work and as far as I know, you need the following:

1. Create a github account
2. Edit files of some sort manually
3. Create a fork? (I am unsure whether this is needed, or if there is a way to circumvent this)
4. Create a commit (even for tech people, commit messages can be hard and I imagine that they could get quite chaotic)
5. Create a pull request
6. Go through the review?
7. Your suggestion can be merged

Not saying that this is unfeasible (especially since even a simple web app has to be written by someone), it is only a lot more complicated than:

1. Open a web app
2. Log in?
3. Translate / review translation
4. Done

**Comment by 3b1b** [comment]
I couldn't agree more. Of course, creating and maintaining any kind of app is always an investment, so it's worth being sure the more onerous process is truly onerous enough to justify the step up.

**Comment by tintin10q** [comment]
I also agree with this. I would still suggest to store the translations in toml format if there is a web app or not.
