### ISSUE TITLE
Suggestion: Czech

### ISSUE THREAD

**Issue by Chnapak** [3b1b/captions#94]
Hi, I would love to help translate 3B1B videos into Czech. I'm probably going to work backwards and start by translating the Shorts from 2024 and 2023 with the Optics puzzle series if possible:
### **Requested videos for translations**
- barber-pole-1
- barber-pole-2
- cube-shadow-puzzle
- mandelbrot
- newton-art-puzzle
- on-shorts
- prism
- refractive-index-questions
- subset-sum

I have already translated cube-shadow-puzzle without the rough translation. Not exactly sure what I'm supposed to do with it now, but I will gladly translate it once more alongside the rough translation if necessary.

SIDE NOTE:
I've noticed there is no #czech channel on the translation Discord server and I would like to ask you to add one. Even though I will be evidently doing solo work there, I'd be good to have things over there organized for future translators.

Hopefully I'll have these translations done in less than a month's worth of time, even thought my progress might be slowed down, because of my school and studying, but I believe the shorts will be a matter of a few days in worst case scenario.

**Comment by 3b1b** [comment]
Thanks for the suggestion, I went ahead and added them for the optics puzzle series.

For what it's worth, I don't really care about shorts. Many of them are in this directory because the were quick and easy to run tests on while setting up the transcription -> translation pipeline, but having dubs for them is not a priority. If you care, though, I can certainly run the script on them as well.
